# COMPSs

vARGS=" \
-v $RAM_PATH:/media/ram \
-v $SSD_PATH:/media/ssd \
-v $HDD_PATH:/media/hdd \
-v $COMPSS_LIB:/home/lib \
-v $MODEL_PATH:/models \
-v $GCI_LOG/compss_bestpractise:/logs \
"
#-v $MODEL_PATH:/models \
#-v /home/daniele.lezzi/Landsupport/granules:/models \

docker run -d --name $container \
--restart always \
--mac-address 12:12:ad:42:09:02 \
--net landsupport_bridge \
--ip=172.18.0.17 \
$vARGS \
-p46600:46600 \
-p46402:46402 \
-t $container > /dev/null

