vARGS=" \
-v $IN_RAS_DATA:/geodata \
-v /home/release/git/LandSupport/middleware/dockerfiles/era5_land_reanalysis/era5-land:/home/landsupport/era5-land \
-v /home/release/git/LandSupport/middleware/dockerfiles/era5_land_reanalysis/cosmo-leps:/home/landsupport/cosmo-leps \
-v /media/GFTP/landsupport/era5land_download/logs:/logs \
"

docker run -d --name $container \
  --restart=always \
  --mac-address 00:21:dd:03:10:13 \
  --net landsupport_bridge \
  --ip=172.18.0.58 \
  $vARGS \
  -t $container > /dev/null

