# Rasdaman

ras="/home/ras-test"

vARGS=" \
-v $BRANCH_PATH/middleware/api/dockers_rest/docker_run.php:/var/www/html/docker_run.php \
-v $CUBER_PATH:$CUBER_PATH \
-v $IN_RAS_DATA:/geodata \
-v $RAM_PATH:/media/ram \
-v $SSD_PATH:/media/ssd \
-v $HDD_PATH:/media/hdd \
-v $RAS_DB_PATH:$APACHE_ROOT_PATH/db_rasdaman \
-v $DATA_PATH/rasdaman/recipes:$RAS_RECIPE \
-v $ras/data:/opt/rasdaman/data \
-v $ras/etc:/opt/rasdaman/etc \
-v $ras/log:/opt/rasdaman/log \
-v $ras/secore:/secore \
-v $ras/postgres:/var/lib/postgresql/9.5/main \
"

docker run -d --name rasdaman \
--restart=always \
--mac-address 02:42:ac:12:00:04 \
--net landsupport_bridge \
--ip=172.18.0.4 \
-p 3022:22 \
-p 8090:9009 \
-p 8091:9010 \
-p 8092:80 \
$vARGS \
-t $image > /dev/null
