# pp_processor : the brain of the whole LandSupport GCI
#

#UID=3007
#GID=3003

vARGS=" \
-v $BRANCH_PATH/middleware/api/dockers_rest/docker_run.php:/var/www/html/docker_run.php \
-v $BRANCH_PATH/middleware/api/dockers_rest/php.ini:/etc/php.ini \
-v $BRANCH_PATH/middleware:/middleware \
-v $DATA_PATH:/media/GFTP \
-v $RAM_PATH:/media/ram \
-v $SSD_PATH:/media/ssd \
-v $HDD_PATH:/media/hdd \
"

docker run -d --name $container \
--restart always \
--net landsupport_bridge \
$vARGS \
-t test > /dev/null
